### ISSUE TITLE
Only CentOS 8?

### ISSUE THREAD

**Issue by brianjmurrell** [robertdebock/docker-github-action-rpmbuild#6]
Doesn't this https://github.com/robertdebock/docker-github-action-rpmbuild/blob/190ff034b3143395f905246cfb445a3b3484b848/Dockerfile#L1 limit this project to only building CentOS 8 RPMs?

Have you considered introducing [rpm-software-management/mock](https://github.com/rpm-software-management/mock) to allow building for multiple distributions?

**Comment by robertdebock** [comment]
Thanks for the feedback.

In this case, there are many branches for different distributions. These branches result in tagged Docker images.

**Comment by brianjmurrell** [comment]
Oh yes, I see.  I might convert this ticket then to document the nature of the different branches in the README.md.  :-)

I also wonder though if the base docker images might provide "too much" and mask missing `BuildRequires:` the way mock was designed not to.
